Repository TeoSprint15-10/NAVOGUE-FE, pull requests merged in 2023-06, with the labels that each got.

#11 style: 헤더 레이아웃 작업
  public/assets/NAVOGUE.png
  public/assets/logo.svg
  public/assets/searchIcon.png
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/types/custom.d.ts
Labels: 🎨 style

#12 style: 헤더 상단 고정되도록 수정
  src/components/Header/style.ts
Labels: 🎨 style

#16 feat: 메인 페이지 memo 데이터 받아오기
  package.json
  src/api/index.ts
  src/api/memo.ts
  src/components/CardList/index.tsx
  src/components/CardList/style.ts
  src/components/CardWrapper/index.tsx
  src/constants/key.ts
  src/data/memoList.json
  src/hooks/queries/memoList.ts
  src/pages/MainPage/index.tsx
  src/types/index.ts
  yarn.lock
Labels: 🔨 feature

#33 style: 태그 추가 모달UI 구현
  src/components/TagModal/index.tsx
  src/components/TagModal/style.ts
Labels: 🎨 style

#37 style: card element & modal custom hook
  package.json
  public/assets/bookmark.svg
  public/assets/bookmarkFilled.svg
  public/assets/dot.svg
  src/components/Card/CardList/index.tsx
  src/components/Card/CardList/style.ts
  src/components/Card/CardWrapper/index.tsx
  src/components/Card/CardWrapper/style.ts
  src/components/CardList/index.tsx
  src/components/CardWrapper/index.tsx
  src/components/Header/index.tsx
  src/components/SelectedContent/style.ts
  src/data/memoList.json
  src/hooks/useModal.ts
  src/pages/MainPage/index.tsx
  vite.config.ts
  yarn.lock
Labels: 🔨 feature, 🎨 style

#44 feat: 컨텐츠 타입(URL, TEXT)에 따른 필터링
  src/api/memo.ts
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/FilterCheckbox/index.tsx
  src/components/FilterCheckbox/style.ts
  src/components/MemoInputBox/style.ts
  src/hooks/useContentTypeFilter.ts
  src/hooks/useInput.ts
  src/pages/MainPage/index.tsx
  vite.config.ts.timestamp-1687671894502-f700ad1de016f.mjs
Labels: 🔨 feature

#45 feat: 태그 추가 구현
  .env.sample
  src/api/tag.ts
  src/components/TagModal/index.tsx
  src/components/TagModal/style.ts
  src/pages/MainPage/index.tsx
  src/types/index.ts
Labels: 🔨 feature

#50 feat: 메인 페이지 카드 UI 작성 및 Access Token Axios Instance 추가
  .env.sample
  src/api/index.ts
  src/api/memo.ts
  src/components/Card/CardList/index.tsx
  src/components/Card/CardWrapper/index.tsx
  src/components/Card/CardWrapper/style.ts
  src/components/Card/UrlThumbnail/index.tsx
  src/components/Card/UrlThumbnail/style.ts
  src/components/Layout/style.ts
  src/data/memoList.json
  src/pages/MainPage/index.tsx
  src/styles/globalStyle.ts
  src/types/index.ts
  src/types/responseType.ts
  src/utils/memoTypeGuard.ts
Labels: 🔨 feature, 🎨 style

#55 feat: 태그 추가 및 삭제 api 구현
  src/api/tag.ts
  src/components/Header/index.tsx
  src/components/TagModal/index.tsx
  src/pages/MainPage/index.tsx
  src/types/index.ts
Labels: 🔨 feature

#65 feat: 메모 수정기능 구현
  src/components/Card/CardWrapper/index.tsx
Labels: 🔨 feature

#73 feat: 메모수정 기능 수정, 메모 삭제기능 추가
  src/components/Card/CardWrapper/index.tsx
  src/components/Card/CardWrapper/style.ts
Labels: 🔨 feature
